::pipenv run python -m app.main companies.db "SELECT id, name FROM companies WHERE country = 'republic of the congo'" ::chad'"
::'north korea'" 
::''" 
::'eritrea'"
pipenv run python -m app.main sample.db "SELECT COUNT(*) FROM apples"